### ISSUE TITLE
GAR.BIN is in plugins folder (but it's not a plugin).

### ISSUE THREAD

**Issue by zombie343** [bbbradsmith/usbcopynesblue#20]
This is perhaps the most over-thinking a person can do, but I confirmed the MD5 of GAR.BIN in the plugins folder is the same GAR.bin that the Kevin's original CopyNES.zip has in it's root directory. Therefore, I would assume this is the same GAR.BIN that one would use to revive a dead QJ Game Action Replay (SV-801) cart. I will be doing this as soon as I get one in the mail.

GAR.BIN MD5: 5825510305e8b48c434c8b1ec544370e

Why am I posting this issue? Because GAR.BIN isn't actually a plugin (i.e. compiled ASM that is loaded/unloaded) as folder-structure would imply. It is instead the file you would select to revive the dead QJ Game Action Replay (SV-801) Cart.

**Comment by bbbradsmith** [comment]
I'm not sure exactly what you're suggesting... sounds like you think that file should be moved somewhere else? Maybe adding some sentence or two documenting it in a readme? Do you think you could create a pull request that does this, or otherwise describe what should be done?

**Comment by zombie343** [comment]
Correct. Yes, I'd be happy to. Should have a GAR cartridge in hand in 1-2 days to test and confirm.

**Comment by zombie343** [comment]
I haven't forgotten. It's just that the 3 untested GARs I bought were all working. :/ Anyone have a broken Game Action Replay out there?

**Comment by leonkiriliuk** [comment]
CopyNES is able to backup and restore the GAR (8K battery backed SRAM that get wiped when the battery dies, making the GAR useless) CopyNES software never came with GAR.BIN before and I've always used a private GAR.BIN Kevtris gave me over a decade ago to restore dead GAR carts. I don't know if the GAR.BIN file here is valid, but assuming it is, it's in the correct directory given how the CopyNES menu works (where it looks for the file). So I don't understand what the issue here is; is it even an issue?

**Comment by bbbradsmith** [comment]
Closing with no clear problem or proposed action.
